[2020-11-12 12:46:06,806][ERROR][2311976][experiments.py:run_experiment_from_to_file:752] XXX failed 24 DENSITY_VARIATION_EXPERIMENTS_LARGE_ENV/DENSITY_VARIATION_EXPERIMENTS_LARGE_ENV_baseline_2020_11_12T12_43_19/data agent 24 with malfunction ExperimentMalfunction(time_step=27, agent_id=24, malfunction_duration=50). Found earliest=28 for Waypoint(position=(42, 35), direction=2)
[2020-11-12 12:46:06,806][ERROR][2311976][experiments.py:run_experiment_from_to_file:752] XXX failed 24 DENSITY_VARIATION_EXPERIMENTS_LARGE_ENV/DENSITY_VARIATION_EXPERIMENTS_LARGE_ENV_baseline_2020_11_12T12_43_19/data agent 24 with malfunction ExperimentMalfunction(time_step=27, agent_id=24, malfunction_duration=50). Found earliest=28 for Waypoint(position=(42, 35), direction=2)
